catalog-info.yaml

Terrazzo is [blocked on this RRE](https://buildkite.com/elastic/terrazzo/builds/32807#annotation-terrazzo) due to indentation on the properties, this is a pass at attempting to fix that.
https://github.com/elastic/logstash-filter-elastic_integration/blob/c8485e256a5b6f95a738f87d15a0336feb04d033/catalog-info.yaml#L58-L67
This is a super easy mistake to make, the `intermediate_builds` props are part of the overall spec, and not the provider specifications (which confusingly only relate to GitHub hook settings). yaml-language-server was able to catch this using the schema modeline you kindly added, but it helped us identify an issue with rre-cli that will help us provide you with more informative and actionable validation feedback in the future (as opposed to Terrazzo's very vague "something …

Fix accidental property indent on catalog-info.yaml

---

.buildkite/scripts/resolve_es_treeish.sh
catalog-info.yaml

We define `SNAPSHOT` vars under pipeline env and when it is not defined recently introduced `resolve_es_treeish.sh` script crashes at [this point](https://github.com/elastic/logstash-filter-elastic_integration/blob/main/.buildkite/scripts/resolve_es_treeish.sh#L10). This PR sets default value to `SNAPSHOT` when undefined and allows script to run.

Fix: when snapshot env var is undefined, script crashes.

---

.buildkite/pull-requests.json

CI doesn't get kicked of because pipeline slug name is different. This PR changes slug name.

Fix the pipeline slug name.

---

src/main/java/co/elastic/logstash/filters/elasticintegration/EventProcessorBuilder.java

Introduced on Elasticsearch `main` in elastic/elasticsearch#105163 and backported to `8.12` in elastic/elasticsearch#105163. Migrating to this stable API allows our build to work across the 8.12->8.13 boundary in which we observed a change to the ThreadPool's constructor.
Resolves: elastic/logstash-filter-elastic_integration#120
Closes: #121

boundary: use ES API-stable LSIB#createThreadPool

---

docs/index.asciidoc

Just noticed that uri parts processor's name is `uri_parts`: https://www.elastic.co/guide/en/elasticsearch/reference/current/uri-parts-processor.html

Fix uri parts processor type.

---

.buildkite/e2e-pipeline.yml
.buildkite/scripts/run_e2e_tests.sh
catalog-info.yaml

This change setups a BK E2E pipeline for `elastic_integration` plugin. It also includes a shell script to build the plugin before E2E tests start (coming soon with https://github.com/elastic/logstash-filter-elastic_integration/pull/122)

E2E pipeline setup with a plugin build shell script.

---

.buildkite/scripts/run_e2e_tests.sh

This change sets Java home to the path and it is required when building Logstash.

Set Java home to the path where Logstash build requires.

---

src/main/java/co/elastic/logstash/filters/elasticintegration/EventProcessorBuilder.java
src/test/java/co/elastic/logstash/filters/elasticintegration/EventProcessorBuilderTest.java

One possible approach to handling the upstream breaking change in 8.14's PainlessPlugin's provisioning of default base whitelists.
Resolves #135

use reflection to get past breaking change in PainlessPlugin

---

src/main/java/co/elastic/logstash/filters/elasticintegration/geoip/GeoIpDatabaseAdapter.java

Catches up with Elasticsearch 8.14+ support for user-provided databases:
- `Anonymous-IP` elastic/elasticsearch#107287
- `Enterprise` elastic/elasticsearch#107377
When compiled against Elasticsearch < 8.14, these methods neither exist in the interface nor are reachable by the GeoIP processor.
Resolves #138

geoip: implement `GeoIpDatabase` methods added in ES 8.14

---

.ci/docker-run.sh
.ci/docker-setup.sh

Output of buildkite is too noisy given the docker compose tty progress, it can be heavily reduced by switching to `BUILDKIT_PROGRESS=plain`
Before:
```
❯ ls -lha logstash-filter-elastic-integration-pull-request_build_363_hammer-ci-setup-and-integration-tests-with-es-8-dot-x-snapshot-run-on-docker.log
87M Oct 23 09:30 logstash-filter-elastic-integration-pull-request_build_362_hammer-ci-setup-and-integration-tests-with-es-8-dot-x-run-on-docker.log
```
After:
```
❯ ls -lha logstash-filter-elastic-integration-pull-request_build_362_hammer-ci-setup-and-integration-tests-with-es-8-dot-x-run-on-docker.log
72K Oct 23 09:34 logstash-filter-elastic-integration-pull-request_build_363_hammer-ci-setup-and-integration-tests-with-es-8-dot-x-snapshot-run-on-docker.log
```

set buildkit progress to plain to reduce CI noise

---

src/main/java/co/elastic/logstash/filters/elasticintegration/geoip/ConstantIpDatabaseHolder.java
src/main/java/co/elastic/logstash/filters/elasticintegration/geoip/IpDatabaseAdapter.java
src/main/java/co/elastic/logstash/filters/elasticintegration/geoip/IpDatabaseHolder.java
src/main/java/co/elastic/logstash/filters/elasticintegration/geoip/IpDatabaseProvider.java
src/main/java/co/elastic/logstash/filters/elasticintegration/geoip/ManagedIpDatabaseHolder.java
src/test/java/co/elastic/logstash/filters/elasticintegration/geoip/ManagedIpDatabaseHolderTest.java

This is a follow-up to https://github.com/elastic/logstash-filter-elastic_integration/pull/170#pullrequestreview-2400287935, as applied to 8.x
It will need to be forward-ported to `main`.

geoip: managed databases need to be closed when updated

---

CHANGELOG.md

The publisher workflow requires that the `CHANGELOG.md` leads with an entry matching the version, so this will prevent releases on the `main` branch, as desired until we come up with the publish path for Elastic Stack 9.x

prevent releases from `main`

---

.buildkite/build-pipeline.yml
.buildkite/e2e-pipeline.yml
.buildkite/pull-request-pipeline.yml
.buildkite/scripts/run_e2e_tests.sh
.buildkite/scripts/run_tests.sh

- Introduces a change to use the 8.x branch in build CI.
- Renames the CI jobs to provide proper names
More deeper details about these compatibility concept here:
- with build CI: make sure we keep the plugin compatible with
- a) any new 8.x releases
- b) any changes going to be in upcoming future 8.x/minor releases (LS 8.x-SNAPSHOT vs ES main, we may use ES 8.x-SNAPSHOT but we cover it with a) as we are defining the branch in gradle.properties)
- c) any changes going to be in upcoming future major releases (LS main vs ES main)
- with E2E: make sure the plugin doesn't have an issue when running integrations
- a) on across 8.x stack
- b) on across 8.x-SNAPSHOT stack
- c) on main (or future major version)
- with PR CI: every change introduced under the PR should be compatible across
- a) …

Use target branch in build CI. Properly name the CI jobs.

---

.buildkite/build-pipeline.yml
.buildkite/e2e-pipeline.yml
.buildkite/pull-request-pipeline.yml
.ci/docker-run.sh
.ci/docker-setup.sh

This draft PR's goal is to make sure CI status is 🟢 before making any further changes.
- Reflect versions re-definition change: https://github.com/elastic/logstash/blob/main/ci/logstash_releases.json

Fix the CI failures after version definitions in .ci repo.

---

src/main/java/co/elastic/logstash/filters/elasticintegration/IngestPipelineFactory.java
src/test/java/co/elastic/logstash/filters/elasticintegration/ElasticsearchPipelineConfigurationResolverTest.java
src/test/java/co/elastic/logstash/filters/elasticintegration/PipelineConfigurationFactoryTest.java

Recently ES `PipelineConfiguration` class renamed its `getConfigAsMap()` to `getConfig()`. This caused plugin build and this PR applies the ES change. 
- Closes #189 
This change will fail on the CI steps which target ES `8.x` (including snapshot), because `PipelineConfiguration->getConfig(boolean)` interface is _only_ available in ES main.

Sync up with ES main on `PipelineConfiguration` class changes.

---

.github/workflows/pr_backporter.yml
devtools/backport

This PR adds a PR backporter which we need to backport changes to designated base branches when we merge PRs to target branches.

Add a PR backporter

---

.buildkite/pull-request-test-matrix.yml

When we raise PR, we need to test the plugin changes against its base branch across multiple stacks to make sure we do not break the plugin. This PR introduces the pull-request matrix where all `8.series` branches will align on `8.x` map and `main` with `main` accordingly. The matrix entry for `main` covers the upgrade path where `8.last.last` (will be maintained through release cycle) will be always tested against next major, `9.x/main` for now.
[Dynamic job generator PR](https://github.com/elastic/logstash-filter-elastic_integration/pull/199) applies this change with `YAML()` tool which easifies out life.
```
matrix_map = call_url_with_retry(MATRIX_MAP)
matrix_map_yaml = YAML().load(matrix_map.text)
print(f"matrix_map: {matrix_map_yaml['8.x']}")
```

A matrix to define compatibility across stack versions, where CI job generator leverages

---

.buildkite/scripts/build-pipeline/generate-steps.py
.buildkite/scripts/e2e-pipeline/generate-steps.py

Oops, snapshot next stack version can be null since it is only available during the FF. I covered it in the pull-request pipeline and forgot noop placeholder in build/E2E pipeline where this PR covers.
- we don't need to wait or doesn't relate to pull-request CI changes

Generate noop CI step if next (is only available during the FF) is N.A

---

README.md

Adds plugin development notes to the readme.

Add plugin development notes in a readme.

---

CHANGELOG.md
docs/index.asciidoc

This change adds a prerequisites doc section to list up its requirements/expectations.

Add prerequisites doc section.

---

.github/workflows/pr_backporter.yml

Thanks for contributing to Logstash! If you haven't already signed our CLA, here's a handy link: https://www.elastic.co/contributor-agreement/

Rename GH secret.

---

.buildkite/pull-requests.json

`pipeline_slug` key somehow was camelCase in the pull-request.json definition. This PR corrects it.

Fix the pipeline slug key in pull-request.json

---

catalog-info.yaml

This commit stops triggering BK from triggering CI when branches get pushed. We rely on CI for PRs, instead, which is handled by the BK PR Bot.

Don't trigger CI when pushing branches

---

.buildkite/scripts/e2e-pipeline/bootstrap.py
.buildkite/scripts/e2e-pipeline/requirements.txt

We don't have yet the integrations with `elastic_integration` unsupported processors. This PR adds a script to search processors the plugin cannot run.
E2E run: https://buildkite.com/elastic/logstash-filter-elastic-integration-e2e/builds/195

Add an E2E step to scan unsupported processors.

---

spec/unit/elastic_integration_spec.rb

Removes hard coded version in the unit tests and replaces with the plugin version.
Forgot 🤦  removing it in https://github.com/elastic/logstash-filter-elastic_integration/pull/247

Removes the fixed version number and uses plugin version instead in the unit tests.

---

.buildkite/scripts/e2e-pipeline/README.md
.buildkite/scripts/e2e-pipeline/bootstrap.py
.buildkite/scripts/e2e-pipeline/main.py

Simplifies running E2E test script on local by introducing skip set up and integrations to test options.
When first running E2E tests, setup is required. For the next steps setup can be skipped.

Simplify running E2E test script on local.

---

.buildkite/pull-requests.json
.github/workflows/mergify-labels-copier.yml
.github/workflows/pre-commit.yml
.mergify.yml
.pre-commit-config.yaml

* Enable https://docs.mergify.com/workflow for:
- Creating backports automatically using GitHub backport labels when the original PR gets merged.
- Notify when backports are stalled.
- Notify the backports policy
- Create PRs even with conflicts.
* Enable copy GitHub labels from the original PR to the backported PRs. `Mergify` does not support this feature out of the box, see https://github.com/elastic/apm-server/pull/15190
* Enable merge conflict detection. See https://github.com/elastic/apm-server/pull/15319
Use the same backport mechanism as done in some other projects. While still support for the former approach.
- Delete https://github.com/elastic/logstash-filter-elastic_integration/blob/main/.github/workflows/pr_backporter.yml
Relates https://github.com/elastic/logstash/issues/16933

mergify: support backports automation with labels

---

docs/index.asciidoc

A troubleshooting section added, supported processors are revised and unsupported processors list added.

A troubleshooting section added and more doc improvements.

---

.buildkite/scripts/e2e-pipeline/main.py

Our understanding of `'--skip-setup' action='store_true'` seems incorrect that E2E CIs ([example](https://buildkite.com/elastic/logstash-filter-elastic-integration-e2e/builds/204#0195c00d-2767-4bb1-bb45-a0c41d7c3368/60-169)) running with `--skip-setup=True`.
When I take a look at the `store_true`, it seems it automatically _stores_  the default `False` value: https://hg.python.org/cpython/file/2.7/Lib/argparse.py#l861
Similar discussion can be seen here: https://stackoverflow.com/a/8203679

Sets default False value to skip-setup flag.

---

.github/workflows/backport-active.yml
.mergify.yml

Thanks for contributing to Logstash! If you haven't already signed our CLA, here's a handy link: https://www.elastic.co/contributor-agreement/
Adding new way for backporting to active branches using new gh action.

New way of backporting to active branches using gh action

---

build.gradle

Updates `buildElasticsearchLocalDistro` task to display error logs when ES build fails.

Display logs with gradle task logs if ES build fails.

---

docs/index.asciidoc
lib/logstash/filters/elastic_integration.rb
src/main/java/co/elastic/logstash/filters/elasticintegration/ElasticsearchRestClientBuilder.java
src/main/java/co/elastic/logstash/filters/elasticintegration/PluginConfiguration.java
src/test/java/co/elastic/logstash/filters/elasticintegration/ElasticsearchRestClientBuilderTest.java

Introduces `proxy` config to accept proxy URI to connect to Elasticsearch.
- Closes #303 
- For the local test, used [SquidMan](https://squidman.net/resources/downloads/)
- Config
```
// generator
...
filter {
elastic_integration {
id => "es_integ_1"
cloud_id => "my-cloud-id"
api_key => "api-key"
proxy => "http://127.0.0.1:8083"
}
// output
```
- When proxy is stopped, cannot connect to ES
```
[2025-06-05T17:06:16,068][ERROR][logstash.javapipeline    ][main] Pipeline error {:pipeline_id=>"main", :exception=>#<LogStash::ConfigurationError: Fetching Elasticsearch version information failed: Connection refused>, :backtrace=>["/Users/mashhur/Dev/elastic/ls-plugins/logstash-filter-elastic_integration/lib/logstash/filters/elastic_integration.rb:306:in `raise_config_error!'", …
```

Proxy support

---

.mergify.yml

and remove the duplicated configure and use the global defaults.

mergify: support 9.1 branch

---

src/main/java/co/elastic/logstash/filters/elasticintegration/EventProcessorBuilder.java
src/main/java/co/elastic/logstash/filters/elasticintegration/util/PluginProjectResolver.java

Sync up with upstream ES main: apply project ID resolver applied in logstash-bridge ScriptServiceBridge.
Applying as introduced in the logstash-bridge ScriptServiceBridge: https://github.com/elastic/elasticsearch/pull/130578/files#diff-f74baacde87eae5c09e26daf35f888065d68238e2593160179fb937c11d11327R73
~~Soon, this plugin will start using logstash-bridge instead direct `ScriptService` usage.~~ See [the observations](https://github.com/elastic/logstash-filter-elastic_integration/pull/357#discussion_r2255411211) that applying `null` breaks the plugin, so we may need to apply a logic to provide an actual project resolver.

Sync up with upstream ES main: apply project ID resolver to ScriptService.

---

.buildkite/scripts/build-pipeline/generate-steps.py
.buildkite/scripts/e2e-pipeline/generate-steps.py
.buildkite/scripts/pull-request-pipeline/generate-steps.py
.buildkite/scripts/run_tests.sh

This commit updates the buildkite scripts to look in the `.ci` repo in the logstash-plugins org for the new location of logstash releases.
Thanks for contributing to Logstash! If you haven't already signed our CLA, here's a handy link: https://www.elastic.co/contributor-agreement/

Update buildkite script to look for new logstash releases location
